### ISSUE TITLE
Hardware wallet support

### ISSUE THREAD

**Issue by morfj** [hubiinetwork/nahmii-sdk#5]
Current implementation only supports specifying a private key, and that is not compatible with using hardware wallets where the private key never leaves the device. Enhance the `Wallet` class to support using a **async callback** for signing actions.

Probable new Wallet#constructor() signature: `constructor(provider, (private_key|address) [, signature_provider])`

If you don't have the private key, instantiate the Wallet with the address and a signatureProvider function instead.

Payments, Receipts and other classes will support using a Wallet as a signature provider, making the privatekey to sign() functions optional, e.g.: `sign([private_key])`. An argument can be made for removing the private key altogether from the sign function and simply expect the consumer has provided a wallet instance for the private key instead. Opinions?

## Tasks

- [ ] Update Wallet and create a `sign` function.
- [ ] Update Wallet with new constructor
- [ ] Update Wallet#depositEth()
- [ ] Update Wallet#depositToken()
- [ ] Update Payment#sign()
- [ ] Update Receipt#sign()

**Comment by liamaharon** [comment]
I'll be starting on this next week

**Comment by liamaharon** [comment]
ethers.js contains a "Signer API": https://docs.ethers.io/ethers.js/html/api-wallet.html#signer-api

It appears that a _Wallet_ instance extends _Signer_, and implements the following methods using the private key passed into its constructor
- `.getAddress()`
- `.signMessage()`
- `.sendTransaction()`

One way we could allow passing a custom signing function is
- Change our _Wallet_ implementation to extend _ethers.Signer_ instead of _ethers.Wallet_
- If a private key is passed, implement the _Signer_ methods the same way as they would have if the private key was passed to _ethers.Wallet_
- If the user passed custom signing functions, use those to implement the _Signer_ methods instead of those that would have been used if passed a private key

A benefit of this approach is that our _Wallet_ implementation would remain up to spec, so we'll continue being able to use it for things like calling contract methods (eg `tokenContract.approve(clientFund.address, amountBN, options)` without any added complexity .

@morfj please let me know what you think of this approach. This is just one possible route, I'm open to any other alternatives you may have in mind

**Comment by liamaharon** [comment]
Merged #20
